from matplotlib.colors import LinearSegmentedColormap, ListedColormap
from typing import Any, Dict, List, Optional

def register_listed_cmap(colors: List[str], name: str) -> ListedColormap: ...
def register_blended_cmap(colors: List[str], name: str) -> LinearSegmentedColormap: ...
def apply_style() -> None: ...
def apply_custom_colors(colors: List[str], cmap_name: str = ..., **kwargs: Any) -> None: ...
def get_stwx_cmaps(as_hex: bool = ...) -> Dict[str, Any]: ...
def apply_style_altair(n_groups_ordinal: int = ...) -> None: ...
def apply_custom_colors_altair(primary: Optional[str] = ..., category: Optional[List[str]] = ..., diverging: Optional[List[str]] = ..., heatmap: Optional[List[str]] = ..., ramp: Optional[List[str]] = ..., ordinal: Optional[List[str]] = ..., n_groups_ordinal: int = ...) -> None: ...
def apply_style_plotly() -> None: ...
def apply_custom_colors_plotly(category: Optional[List[str]] = ..., diverging: Optional[List[str]] = ..., sequential: Optional[List[str]] = ..., sequential_minus: Optional[List[str]] = ..., heatmap: Optional[List[str]] = ...): ...
