name: Code Quality

on:
  pull_request:
    paths-ignore:
      - docs/**
  push:
    branches: [master, main, dev]
    paths-ignore:
      - docs/**
jobs:
  pre-commit:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
